name: Llama Bot Automated Tests

on:
  push:
    branches:
    - llama2_whatsapp_integration

  pull_request:
    branches:
    - llama2_whatsapp_integration

# Automatically cancel previous workflows if a new one is executed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Python Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12" 
          architecture: "x64" 

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Python version and dependency list
        run: |
          python --version
          which python
          pip list

      - name: Run unittests
        run: |
          python tests/unit/test_unit.py
          # python tests/unit/test_integration.py
