name: Deploy Chatbot Application to Azure App Service

on:
  push:
    branches:
      - main  # Or your default branch, e.g., master

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Ensure this matches your project's Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        pytest tests/unit/

    - name: Run Integration Tests
      run: |
        pytest tests/integration/

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Azure service principal JSON details

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: eu-report-chatbot  # Your Azure App Service name
        slot-name: 'production'  # Optional: specify if using deployment slots
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Publish profile from Azure
        package: '.'  # Path to your project directory, adjust if necessary

