name: Deploy Contracts and Update Config

on:
  push:
    branches:
      - polygon-storage

jobs:
  deploy_and_update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: Install Dependencies
      run: npm install
    - name: Deploy Contracts to Network
      run: npx truffle migrate --network mumbai
      env:
        INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
        MNEMONIC: ${{ secrets.MNEMONIC }}
    - name: Extract Contract Details
      run: bash ./scripts/extract_contract_details.sh

            
      