name: PR gate

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    input:
      tags:
        description: "Tags to label this manual run (optional)"
        default: "Manual run"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Python Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Replace 'x' with the specific version you're using
          architecture: "x64" # Adjust this if you're using a different architecture

      - name: Install dependencies
        run: |
          pip install .
          pip install pytest # If you haven't installed pytest yet, unittest does not need this

      - name: Python version and dependency list
        run: |
          python --version
          which python
          pip list

      - name: Run unittests
        run: |
          python tests/unit/test_app.py
          python tests/unit/test_commands.py
          python tests/integration/test_integration.py
